language: python

env:
  global:
    - GITHUB_REPO: plugin.video.altv
    - ZIP_FILENAME: plugin.video.altv-${TRAVIS_TAG:1}.zip

before_script:
  - cd ..
  - mv $GITHUB_REPO plugin.video.altv

script:
  - echo ${ZIP_FILENAME}
  - zip $ZIP_FILENAME -x "*/.*" "*/docs/*" "*/*.pyc" "*/*.pyo" "*/*.pyo" -r ./plugin.video.altv

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file: ${ZIP_FILENAME}
  skip_cleanup: true # Prevent Travis from deleting files created during build to use for upload
  on:
    tags: true # Required to make sure that tags get deployed