language: python

env:
  global:
    - GITHUB_REPO: plugin.video.altv
    - ZIP_FILENAME: plugin.video.altv-${TRAVIS_TAG:1}.zip

before_script:
  - cd .. # Change directory one level up in order to compress the folder to publish as release

script:
  - echo ${ZIP_FILENAME}
  - zip $ZIP_FILENAME -x "*/.*" "*/docs/*" "*/*.pyc" "*/*.pyo" "*/*.pyo" "*/tests/*" -r ./${GITHUB_REPO}

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file: ${ZIP_FILENAME}
  skip_cleanup: true # Prevent Travis from deleting files created during build to use for upload
  on:
    tags: true # Required to make sure that tags get deployed