language: python
python:
  - "2.7"

# script:

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file: plugin.video.altv-${TRAVIS_TAG:1}.zip
  skip_cleanup: true # Prevent Travis from deleting files created during build to use for upload
  on:
    tags: true